app:
  config:
    drones:
      base-uri: /drones
      api:
         register: /api/v1/registerdrone
         available: /api/v1/availabledrones
         batterylevel: /api/v1/batterylevel/{serialNumber}
         alldrones: /api/v1/alldrones
         loaddrone: /api/v1/loaddrone
         updatestatus: /api/v1/updatestatus
    medications:
      base-uri: /medications
      api:
        register: /api/v1/registermedication
        check-loaded-item: /api/v1/loadeditem/{droneSerialNumber}
spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    repositories:
      bootstrap-mode: default


server:
  port: 8080
  error.include-message: always
springdoc:
  show-actuator: true
  packagesToScan: com.musala.drones
  operations-sorter: alpha